language: c

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      python: 2.7.10
      env: OS=macos
    - os: linux
      env: OS=linux
  allow_failures:
    - env: OS=linux
  fast_finish: true

script: bash ${TRAVIS_BUILD_DIR}/test/travis.bash $OS
